name: Update Kubernetes Manifests

on:
  workflow_run:
    workflows: ["Build and Push Container Image"]
    types:
      - completed
    branches:
      - main
      - develop

env:
  GITOPS_REPO: ${{ github.repository }}
  GITOPS_REPO_BRANCH: main

jobs:
  update-manifests:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GITOPS_REPO_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2
        
      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
          
          # Generate image tag from commit SHA
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "image_tag=main-${SHORT_SHA}" >> $GITHUB_OUTPUT
          
      - name: Update image tag in Kustomize overlay
        env:
          ENVIRONMENT: ${{ steps.env.outputs.environment }}
          IMAGE_TAG: ${{ steps.env.outputs.image_tag }}
        run: |
          cd lab-k8s/04-tools-ecosystem/04-gitops/examples/guestbook/overlays/${ENVIRONMENT}
          
          # Update image tag using kustomize
          kustomize edit set image gcr.io/google-samples/gb-frontend:${IMAGE_TAG}
          
          # Show changes
          echo "Updated kustomization.yaml:"
          cat kustomization.yaml
          
      - name: Commit and push changes
        env:
          ENVIRONMENT: ${{ steps.env.outputs.environment }}
          IMAGE_TAG: ${{ steps.env.outputs.image_tag }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add lab-k8s/04-tools-ecosystem/04-gitops/examples/guestbook/overlays/${ENVIRONMENT}/kustomization.yaml
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          
          git commit -m "chore(gitops): update guestbook ${ENVIRONMENT} image to ${IMAGE_TAG}

          Updated by GitHub Actions workflow
          Triggered by: ${{ github.event.workflow_run.head_commit.message }}
          Commit: ${{ github.sha }}"
          
          git push
          
      - name: Create deployment annotation
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: `✅ GitOps manifest updated for **${{ steps.env.outputs.environment }}** environment\n\nImage tag: \`${{ steps.env.outputs.image_tag }}\`\n\nArgoCD will sync the changes automatically.`
            });
