# Init Container - Git Clone Example
# Clone a git repository before starting the application

apiVersion: v1
kind: Pod
metadata:
  name: git-clone-pod
  labels:
    app: static-site
    pattern: git-clone
spec:
  initContainers:
  # Clone git repository into shared volume
  - name: git-clone
    image: alpine/git:2.40.1
    command:
    - 'sh'
    - '-c'
    - |
      echo "Cloning repository..."
      git clone --depth 1 --branch main \
        https://github.com/example/website.git /data
      echo "Repository cloned successfully!"
      ls -la /data
    volumeMounts:
    - name: git-data
      mountPath: /data
    env:
    # For private repositories, use credentials from Secret
    - name: GIT_USERNAME
      valueFrom:
        secretKeyRef:
          name: git-credentials
          key: username
          optional: true
    - name: GIT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: git-credentials
          key: password
          optional: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  
  # Install dependencies (if needed)
  - name: install-deps
    image: node:20-alpine
    command:
    - 'sh'
    - '-c'
    - |
      cd /data
      if [ -f package.json ]; then
        echo "Installing npm dependencies..."
        npm install --production
        echo "Dependencies installed!"
      else
        echo "No package.json found, skipping..."
      fi
    volumeMounts:
    - name: git-data
      mountPath: /data
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
  
  # Build static site (if needed)
  - name: build-site
    image: node:20-alpine
    command:
    - 'sh'
    - '-c'
    - |
      cd /data
      if [ -f package.json ] && grep -q "build" package.json; then
        echo "Building site..."
        npm run build
        echo "Build completed!"
      else
        echo "No build script found, skipping..."
      fi
    volumeMounts:
    - name: git-data
      mountPath: /data
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
  
  # Main container: Serve the static site
  containers:
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
      name: http
    volumeMounts:
    # Mount the cloned and built site
    - name: git-data
      mountPath: /usr/share/nginx/html
      readOnly: true
    # Custom nginx configuration
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
  
  volumes:
  # Shared volume for git data
  - name: git-data
    emptyDir: {}
  # Nginx configuration
  - name: nginx-config
    configMap:
      name: nginx-static-config

---
# Secret for git credentials (optional, for private repos)
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
type: Opaque
stringData:
  username: "git-user"
  password: "git-token-or-password"

---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-static-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;
        
        # Enable gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        
        # Cache static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
        
        # SPA routing (if applicable)
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
