#!/bin/bash

# Test alert firing by creating a test alert

set -e

echo "🧪 Testing alert flow..."

# Check if Alertmanager is running
if ! curl -s http://localhost:9093/-/healthy > /dev/null; then
    echo "❌ Alertmanager is not running. Please start it first."
    exit 1
fi

echo "✓ Alertmanager is healthy"

# Send a test alert to Alertmanager
echo "📤 Sending test alert to Alertmanager..."

curl -X POST http://localhost:9093/api/v2/alerts \
  -H 'Content-Type: application/json' \
  -d '[
    {
      "labels": {
        "alertname": "TestAlert",
        "severity": "warning",
        "service": "test-service",
        "team": "platform"
      },
      "annotations": {
        "summary": "This is a test alert",
        "description": "This alert was generated by the test script to verify the alert flow.",
        "impact": "No impact - this is a test",
        "runbook_url": "https://runbooks.example.com/test-alert"
      },
      "startsAt": "'$(date -u +%Y-%m-%dT%H:%M:%S.000Z)'",
      "endsAt": "'$(date -u -d '+5 minutes' +%Y-%m-%dT%H:%M:%S.000Z)'"
    }
  ]'

echo ""
echo "✅ Test alert sent!"
echo ""
echo "Check the following:"
echo "  1. Alertmanager UI: http://localhost:9093/#/alerts"
echo "  2. Slack channel (if configured)"
echo "  3. PagerDuty (if configured)"
echo ""
echo "The alert will auto-resolve in 5 minutes."
