apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: fake-store
    kind: ClusterSecretStore
  target:
    name: my-k8s-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: /prod/database
      property: username
  - secretKey: password
    remoteRef:
      key: /prod/database
      property: password
