apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake-store
spec:
  provider:
    fake:
      data:
      - key: "/prod/database"
        version: "v1"
        data:
          username: "admin"
          password: "supersecretpassword"
