# ============================================================================
# ARGOCD APPLICATION MANIFEST
# ============================================================================
# File: argocd-gitops/applications/my-app.yaml
# Purpose: ArgoCD Application definition for GitOps deployment
# ============================================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  # Finalizer to ensure proper cleanup
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project this application belongs to
  project: default
  
  # Source repository configuration
  source:
    # Git repository URL containing Kubernetes manifests
    repoURL: https://github.com/your-org/gitops-repo.git
    targetRevision: main
    path: manifests/dev
    
    # Helm configuration (if using Helm charts)
    # helm:
    #   valueFiles:
    #     - values-dev.yaml
  
  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  
  # Sync policy
  syncPolicy:
    # Automated sync configuration
    automated:
      # Automatically sync when Git changes detected
      prune: true
      # Automatically sync when application is out of sync
      selfHeal: true
      # Allow empty resources
      allowEmpty: false
    
    # Sync options
    syncOptions:
      # Create namespace if it doesn't exist
      - CreateNamespace=true
      # Validate resources before applying
      - Validate=true
      # Use server-side apply
      - ServerSideApply=true
    
    # Retry configuration
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
