# jenkins-infra/jenkins.yaml
jenkins:
  systemMessage: "Managed by JCasC"
  numExecutors: 0
  mode: EXCLUSIVE
  scmCheckoutRetryCount: 2
  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

tool:
  git:
    installations:
      - name: "Default"
        home: "git"

jobs:
  - script: >
      job('seed-job') {
        scm {
          git {
            remote {
              url('https://github.com/myorg/jenkins-infra.git')
            }
            branch('main')
          }
        }
        steps {
          dsl {
            external('jobs/*.groovy')
            removeAction('DELETE')
          }
        }
      }

unclassified:
  location:
    url: "http://localhost:8080/"
    adminAddress: "admin@example.com"
