# Secret Examples
# Store sensitive data (passwords, tokens, keys)
# Data is base64 encoded (not encrypted by default, unless encryption-at-rest is enabled)

# Example 1: Opaque Secret (Generic)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # echo -n "admin" | base64 => YWRtaW4=
  username: YWRtaW4=
  # echo -n "password123" | base64 => cGFzc3dvcmQxMjM=
  password: cGFzc3dvcmQxMjM=

---
# Example 2: TLS Secret
# Used for Ingress TLS termination
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
type: kubernetes.io/tls
data:
  # Public certificate (base64)
  tls.crt: LS0tLS1CRUdJTiBDRV...
  # Private key (base64)
  tls.key: LS0tLS1CRUdJTiBQUk...

---
# Example 3: Docker Registry Secret
# Used for pulling images from private registries
apiVersion: v1
kind: Secret
metadata:
  name: my-registry-key
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IH...

---
# Example 4: Pod using Secret as Env Vars
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "env"]
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password

---
# Example 5: Pod mounting Secret as Volume
# Files are decoded automatically when mounted
apiVersion: v1
kind: Pod
metadata:
  name: secret-vol-pod
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: secret-vol
      mountPath: /etc/secret-volume
      readOnly: true
  volumes:
  - name: secret-vol
    secret:
      secretName: db-credentials
