apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/YOUR_USERNAME/gitops-lab-config.git
    targetRevision: main
    path: apps/guestbook/overlays/staging
  
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  
  # Semi-automated sync for staging - auto-sync but no self-heal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false    # Manual changes allowed in staging
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
