# Multi-Container Pod Example
# Demonstrates multiple containers running in the same pod, sharing network and storage

apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: webapp
    pattern: multi-container
  annotations:
    description: "Web application with nginx frontend and app backend"
spec:
  # Multiple containers in the same pod share:
  # 1. Network namespace (localhost communication)
  # 2. IPC namespace
  # 3. Volumes
  containers:
  
  # Container 1: Nginx web server (frontend)
  - name: nginx
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
      name: http
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    # Mount shared volume for static files
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    # Nginx configuration via ConfigMap
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  
  # Container 2: Application backend
  - name: app
    image: python:3.11-slim
    command: ["python", "-m", "http.server", "8000"]
    workingDir: /app
    ports:
    - containerPort: 8000
      name: app-port
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "256Mi"
        cpu: "400m"
    # Mount shared volume for application files
    volumeMounts:
    - name: shared-data
      mountPath: /app
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    # Liveness probe for app container
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 15
      periodSeconds: 10
  
  # Container 3: Log collector (sidecar)
  - name: log-collector
    image: busybox:1.36
    # Tail logs from shared volume
    command: ["sh", "-c", "tail -f /var/log/app/*.log"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
    volumeMounts:
    - name: log-volume
      mountPath: /var/log/app
  
  # Shared volumes between containers
  volumes:
  # EmptyDir: Temporary storage, deleted when pod is removed
  - name: shared-data
    emptyDir: {}
  
  # EmptyDir for logs
  - name: log-volume
    emptyDir: {}
  
  # ConfigMap volume for nginx configuration
  - name: nginx-config
    configMap:
      name: nginx-config
      optional: true

---
# ConfigMap for nginx configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
        
        # Proxy requests to app container on localhost:8000
        location /api {
            proxy_pass http://localhost:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
