# Build Stage Template
# Reusable build configuration

.build-template:
  stage: build
  image: node:18-alpine
  before_script:
    - echo "Installing dependencies..."
    - npm ci --cache .npm --prefer-offline
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
      - .npm/
  artifacts:
    paths:
      - dist/
      - build/
    expire_in: 1 day

# Concrete build job
build:
  extends: .build-template
  script:
    - echo "Building application..."
    - npm run build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG'

# Build documentation
build-docs:
  extends: .build-template
  script:
    - echo "Building documentation..."
    - npm run docs:build
  artifacts:
    paths:
      - docs/build/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
