# Kubernetes Deployment Template
# Deploy to Kubernetes using kubectl and Helm

.deploy-k8s-template:
  stage: deploy
  image: bitnami/kubectl:latest
  before_script:
    - kubectl version --client

# Deploy review app
deploy-review:
  extends: .deploy-k8s-template
  variables:
    NAMESPACE: "review-$CI_COMMIT_REF_SLUG"
  script:
    - kubectl create namespace $NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
    - kubectl apply -f k8s/ -n $NAMESPACE
    - kubectl set image deployment/$CI_PROJECT_NAME app=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -n $NAMESPACE
    - kubectl rollout status deployment/$CI_PROJECT_NAME -n $NAMESPACE --timeout=5m
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: https://$CI_COMMIT_REF_SLUG.review.example.com
    on_stop: stop-review
    auto_stop_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stop-review:
  extends: .deploy-k8s-template
  variables:
    NAMESPACE: "review-$CI_COMMIT_REF_SLUG"
    GIT_STRATEGY: none
  script:
    - kubectl delete namespace $NAMESPACE --ignore-not-found=true
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  when: manual
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

# Deploy to staging
deploy-staging:
  extends: .deploy-k8s-template
  script:
    - kubectl set image deployment/$CI_PROJECT_NAME app=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -n staging
    - kubectl rollout status deployment/$CI_PROJECT_NAME -n staging --timeout=5m
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Deploy to production
deploy-production:
  extends: .deploy-k8s-template
  script:
    - kubectl set image deployment/$CI_PROJECT_NAME app=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG -n production
    - kubectl rollout status deployment/$CI_PROJECT_NAME -n production --timeout=10m
  environment:
    name: production
    url: https://example.com
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

# Helm deployment template
.deploy-helm-template:
  stage: deploy
  image: alpine/helm:latest
  before_script:
    - helm version

deploy-helm-staging:
  extends: .deploy-helm-template
  script:
    - helm upgrade --install $CI_PROJECT_NAME ./helm
        --namespace staging
        --create-namespace
        --set image.repository=$CI_REGISTRY_IMAGE
        --set image.tag=$CI_COMMIT_SHORT_SHA
        --set ingress.host=staging.example.com
        --wait
        --timeout 5m
  environment:
    name: staging
    url: https://staging.example.com
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy-helm-production:
  extends: .deploy-helm-template
  script:
    - helm upgrade --install $CI_PROJECT_NAME ./helm
        --namespace production
        --create-namespace
        --set image.repository=$CI_REGISTRY_IMAGE
        --set image.tag=$CI_COMMIT_TAG
        --set ingress.host=example.com
        --wait
        --timeout 10m
  environment:
    name: production
    url: https://example.com
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'
