# Test Stage Template
# Reusable test configurations

.test-template:
  stage: test
  image: node:18-alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/
    policy: pull

# Unit tests
unit-test:
  extends: .test-template
  script:
    - echo "Running unit tests..."
    - npm run test:unit -- --coverage
  coverage: '/Lines\s*:\s*(\d+\.\d+)%/'
  artifacts:
    when: always
    reports:
      junit: junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 30 days

# Integration tests
integration-test:
  extends: .test-template
  services:
    - postgres:15-alpine
    - redis:7-alpine
  variables:
    POSTGRES_DB: testdb
    POSTGRES_USER: testuser
    POSTGRES_PASSWORD: testpass
    DATABASE_URL: "postgresql://testuser:testpass@postgres:5432/testdb"
  script:
    - echo "Running integration tests..."
    - npm run test:integration
  artifacts:
    when: on_failure
    paths:
      - logs/
    expire_in: 1 week

# End-to-end tests
e2e-test:
  extends: .test-template
  image: mcr.microsoft.com/playwright:latest
  script:
    - echo "Running E2E tests..."
    - npx playwright test
  artifacts:
    when: on_failure
    paths:
      - test-results/
      - playwright-report/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: '$CI_COMMIT_TAG'

# Linting
lint:
  extends: .test-template
  script:
    - echo "Running linters..."
    - npm run lint
    - npm run format:check
  allow_failure: false
