# Pod Security Standards Examples
# Demonstrates Privileged, Baseline, and Restricted security profiles

# Pod Security Standards (PSS) replaced Pod Security Policies (PSP) in Kubernetes 1.25+
# Three levels: Privileged, Baseline, Restricted

# Example 1: Privileged Pod (least restrictive)
# Allows known privilege escalations
apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
  labels:
    security-level: privileged
  annotations:
    description: "Privileged pod with full host access"
spec:
  containers:
  - name: privileged-container
    image: nginx:1.25-alpine
    # Privileged mode gives container access to all devices
    securityContext:
      privileged: true
      # Can run as root
      runAsUser: 0
      # Can escalate privileges
      allowPrivilegeEscalation: true
      # Has all capabilities
      capabilities:
        add:
        - ALL
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  # Can access host network
  hostNetwork: true
  # Can access host PID namespace
  hostPID: true
  # Can access host IPC namespace
  hostIPC: true

---
# Example 2: Baseline Pod (minimally restrictive)
# Prevents known privilege escalations
apiVersion: v1
kind: Pod
metadata:
  name: baseline-pod
  labels:
    security-level: baseline
spec:
  containers:
  - name: app
    image: nginx:1.25-alpine
    ports:
    - containerPort: 80
    securityContext:
      # Cannot be privileged
      privileged: false
      # Should not run as root (but allowed in baseline)
      runAsUser: 1000
      runAsGroup: 3000
      # Prevent privilege escalation
      allowPrivilegeEscalation: false
      # Drop dangerous capabilities
      capabilities:
        drop:
        - ALL
        add:
        - NET_BIND_SERVICE  # Allow binding to ports < 1024
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  # No host namespace access
  hostNetwork: false
  hostPID: false
  hostIPC: false

---
# Example 3: Restricted Pod (most restrictive)
# Heavily restricted, follows current Pod hardening best practices
apiVersion: v1
kind: Pod
metadata:
  name: restricted-pod
  labels:
    security-level: restricted
spec:
  # Security context at pod level
  securityContext:
    # Must run as non-root
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    # Use seccomp profile
    seccompProfile:
      type: RuntimeDefault
  
  containers:
  - name: app
    image: nginx:1.25-alpine
    ports:
    - containerPort: 8080  # Non-privileged port
    
    # Security context at container level
    securityContext:
      # Must run as non-root
      runAsNonRoot: true
      runAsUser: 1000
      # Prevent privilege escalation
      allowPrivilegeEscalation: false
      # Read-only root filesystem
      readOnlyRootFilesystem: true
      # Drop all capabilities
      capabilities:
        drop:
        - ALL
    
    # Since root filesystem is read-only, mount writable volumes where needed
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: cache
      mountPath: /var/cache/nginx
    - name: run
      mountPath: /var/run
    
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  
  volumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}

---
# Example 4: Namespace with Pod Security Standards
# Apply security standards at namespace level
apiVersion: v1
kind: Namespace
metadata:
  name: restricted-namespace
  labels:
    # Enforce restricted security standard
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    # Audit baseline violations
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/audit-version: latest
    # Warn on baseline violations
    pod-security.kubernetes.io/warn: baseline
    pod-security.kubernetes.io/warn-version: latest

---
# Example 5: Production-Ready Secure Pod
apiVersion: v1
kind: Pod
metadata:
  name: production-secure-pod
  labels:
    app: secure-webapp
    environment: production
spec:
  # Pod-level security
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  
  # Service account with minimal permissions
  serviceAccountName: webapp-sa
  automountServiceAccountToken: false  # Don't auto-mount if not needed
  
  containers:
  - name: webapp
    image: myapp:1.0.0
    ports:
    - containerPort: 8080
    
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    
    # Environment variables from secrets
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-credentials
          key: password
    
    volumeMounts:
    - name: tmp
      mountPath: /tmp
    - name: app-data
      mountPath: /app/data
    
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    
    # Health checks
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5
  
  volumes:
  - name: tmp
    emptyDir: {}
  - name: app-data
    persistentVolumeClaim:
      claimName: app-data-pvc

---
# Example 6: AppArmor Profile
# Linux security module for mandatory access control
apiVersion: v1
kind: Pod
metadata:
  name: apparmor-pod
  annotations:
    # Apply AppArmor profile to container
    container.apparmor.security.beta.kubernetes.io/app: localhost/k8s-apparmor-example
spec:
  containers:
  - name: app
    image: nginx:1.25-alpine
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL

---
# Example 7: SELinux Context
# Security-Enhanced Linux context
apiVersion: v1
kind: Pod
metadata:
  name: selinux-pod
spec:
  securityContext:
    seLinuxOptions:
      level: "s0:c123,c456"
      role: "sysadm_r"
      type: "sysadm_t"
      user: "system_u"
  containers:
  - name: app
    image: nginx:1.25-alpine
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000

---
# Example 8: Seccomp Profile
# Secure computing mode - restricts system calls
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-pod
spec:
  securityContext:
    # Use runtime default seccomp profile
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: app
    image: nginx:1.25-alpine
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL

---
# Custom seccomp profile
apiVersion: v1
kind: Pod
metadata:
  name: custom-seccomp-pod
spec:
  securityContext:
    seccompProfile:
      type: Localhost
      localhostProfile: profiles/audit.json
  containers:
  - name: app
    image: nginx:1.25-alpine

---
# Example 9: Security Best Practices Checklist
apiVersion: v1
kind: Pod
metadata:
  name: security-best-practices
  labels:
    app: secure-app
spec:
  # ✅ Pod-level security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  
  # ✅ Minimal service account
  serviceAccountName: minimal-sa
  automountServiceAccountToken: false
  
  containers:
  - name: app
    # ✅ Use specific image tags, not latest
    image: myapp:1.2.3
    
    # ✅ Container security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    
    # ✅ Resource limits
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "400m"
    
    # ✅ Health checks
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    
    # ✅ Secrets from Kubernetes Secrets
    env:
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: api-credentials
          key: api-key
    
    # ✅ Writable volumes for read-only filesystem
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  
  volumes:
  - name: tmp
    emptyDir: {}
