# 05-kubernetes-deployment/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
type: Opaque
data:
  # Base64 encoded values
  DB_PASSWORD: "c3VwZXJzZWNyZXRwYXNzd29yZA==" # supersecretpassword
  API_KEY: "MTIzNDU2Nzg5MA==" # 1234567890
